spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
  #session存储介质
  session:
    store-type: none


#关闭spring security 的默认密码
security:
  basic:
    enabled: true

server:
  port: 80


zc:
  security:
    browser:
      loginPage: /error/login_t.html
      loginType: JSON
      signUpUrl: /error/t_sing_up.html
    code:
      image:
        url: /user/1,/user/2
      sms:
        url: /user/3,/user/4
    social:
      qq:
        appId:
        appSecret:
      wx:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        providerId: weixin